---
title: "MEMORE_vs_wsMed"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MEMORE_vs_wsMed}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# introduction

This document presents a comparison between the **MEMORE 3.0 (SPSS Plugin)** and **wsMed (R Package)** outputs.

## parallel mediation 

We analyze a **three-mediator parallel mediation model**, comparing the results obtained from both methods. 

### MEMORE 3.0 Analysis Report


````
## ```
##  
## Run MATRIX procedure:
## 
## *********************** MEMORE Procedure for SPSS Version 3.0 ***********************
## 
##                            Written by Amanda Montoya
## 
##                     Documentation available at github.com/akmontoya/MEMORE
## 
## **************************** ANALYSIS NOTES AND WARNINGS ****************************
## 
## Bootstrap confidence interval method used: Percentile bootstrap.
## 
## Number of bootstrap samples for bootstrap confidence intervals:
##   5000
## 
## The following variables were mean centered prior to analysis:
##  (        A2        +       A1       )        /2
##  (        B2        +       B1       )        /2
##  (        C2        +       C1       )        /2
## 
## Level of confidence for all confidence intervals in output:
##       95.00
## 
## **************************************************************************************
## 
## Model:
##   1
## 
## Variables:
## Y =   D2       D1
## M1 =  A2       A1
## M2 =  B2       B1
## M3 =  C2       C1
## 
## Computed Variables:
## Ydiff =           D2        -       D1
## M1diff =          A2        -       A1
## M2diff =          B2        -       B1
## M3diff =          C2        -       C1
## M1avg  = (        A2        +       A1       )        /2                         Centered
## M2avg  = (        B2        +       B1       )        /2                         Centered
## M3avg  = (        C2        +       C1       )        /2                         Centered
## 
## Sample Size:
##   100
## 
## **************************************************************************************
## Outcome: Ydiff =  D2        -       D1
## 
## Model
##                Coef         SE          t          p       LLCI       ULCI
## constant     -.0316      .0170    -1.8586      .0661     -.0653      .0021
## 
## Degrees of freedom for all regression coefficient estimates:
##   99
## 
## **************************************************************************************
## Outcome: M1diff = A2        -       A1
## 
## Model
##                Coef         SE          t          p       LLCI       ULCI
## constant     -.0271      .0176    -1.5385      .1271     -.0621      .0079
## 
## Degrees of freedom for all regression coefficient estimates:
##   99
## 
## **************************************************************************************
## Outcome: M2diff = B2        -       B1
## 
## Model
##                Coef         SE          t          p       LLCI       ULCI
## constant      .0145      .0181      .8024      .4243     -.0213      .0503
## 
## Degrees of freedom for all regression coefficient estimates:
##   99
## 
## **************************************************************************************
## Outcome: M3diff = C2        -       C1
## 
## Model
##                Coef         SE          t          p       LLCI       ULCI
## constant      .0153      .0163      .9404      .3493     -.0170      .0477
## 
## Degrees of freedom for all regression coefficient estimates:
##   99
## 
## **************************************************************************************
## Outcome: Ydiff =  D2        -       D1
## 
## Model Summary
##           R       R-sq        MSE          F        df1        df2          p
##       .1978      .0391      .0296      .6312     6.0000    93.0000      .7049
## 
## Model
##                Coef         SE          t          p       LLCI       ULCI
## constant     -.0315      .0176    -1.7875      .0771     -.0665      .0035
## M1diff       -.0501      .1009     -.4968      .6205     -.2505      .1502
## M2diff       -.0844      .1022     -.8252      .4114     -.2874      .1187
## M3diff       -.0167      .1084     -.1536      .8782     -.2320      .1987
## M1avg        -.0305      .1015     -.3002      .7647     -.2320      .1711
## M2avg        -.0060      .0945     -.0633      .9497     -.1936      .1816
## M3avg        -.1552      .1090    -1.4239      .1578     -.3716      .0612
## 
## Degrees of freedom for all regression coefficient estimates:
##   93
## 
## ************************* TOTAL, DIRECT, AND INDIRECT EFFECTS *************************
## 
## Total effect of X on Y
##      Effect         SE          t         df          p       LLCI       ULCI
##      -.0316      .0170    -1.8586    99.0000      .0661     -.0653      .0021
## 
## Direct effect of X on Y
##      Effect         SE          t         df          p       LLCI       ULCI
##      -.0315      .0176    -1.7875    93.0000      .0771     -.0665      .0035
## 
## Indirect Effect of X on Y through M
##           Effect     BootSE   BootLLCI   BootULCI
## Ind1       .0014      .0030     -.0049      .0078
## Ind2      -.0012      .0029     -.0088      .0035
## Ind3      -.0003      .0028     -.0072      .0050
## Total     -.0001      .0054     -.0130      .0092
## 
## Indirect Key
## Ind1  'X'      ->       M1diff   ->       Ydiff
## Ind2  'X'      ->       M2diff   ->       Ydiff
## Ind3  'X'      ->       M3diff   ->       Ydiff
## 
## Pairwise Contrasts Between Specific Indirect Effects
##           Effect     BootSE   BootLLCI   BootULCI
## (C1)       .0026      .0039     -.0053      .0113
## (C2)       .0016      .0043     -.0067      .0114
## (C3)      -.0010      .0038     -.0089      .0068
## 
## Contrast Key:
## (C1)  Ind1      -       Ind2
## (C2)  Ind1      -       Ind3
## (C3)  Ind2      -       Ind3
## 
## ------ END MATRIX -----
##  
## ```
````

### wsMed Analysis Report


```
## ℹ Loading wsMed
```

```
## 
## *************** VARIABLES ***************
## Variables:
## Y =  D2 D1 
## M1 =  A2 A1 
## M2 =  B2 B1 
## M3 =  C2 C1 
## 
## Computed Variables:
## 
## 
## | Variable|                  Formula|
## |--------:|------------------------:|
## |    Ydiff|                  D2 - D1|
## |   M1diff|                  A2 - A1|
## |   M2diff|                  B2 - B1|
## |   M3diff|                  C2 - C1|
## |    M1avg| ( A2 + A1 ) / 2 Centered|
## |    M2avg| ( B2 + B1 ) / 2 Centered|
## |    M3avg| ( C2 + C1 ) / 2 Centered|
## 
## Sample Size:  100 
## Confidence Level:  95 %
## 
## 
## *************** MODEL FIT INDICES ***************
## 
## 
## |            Measure|   Value|
## |------------------:|-------:|
## |         Chi-Square| 16.2749|
## | Degrees of Freedom| 12.0000|
## |            p-Value|  0.1790|
## |                CFI|  0.0000|
## |                TLI| -1.8293|
## |              RMSEA|  0.0597|
## |     RMSEA Lower CI|  0.0000|
## |     RMSEA Upper CI|  0.1258|
## |               SRMR|  0.0720|
## 
## *************** REGRESSION PATHS, INTERCEPTS AND VARIANCES ***************
## 
## 
## |           Path| Label| Estimate|     SE|       z| P.value|    LLCI|   ULCI|
## |--------------:|-----:|--------:|------:|-------:|-------:|-------:|------:|
## | Ydiff ~ M1diff|    b1|  -0.0501| 0.0957| -0.5240|  0.6003| -0.2392| 0.1374|
## | Ydiff ~ M2diff|    b2|  -0.0844| 0.1038| -0.8127|  0.4164| -0.2823| 0.1204|
## | Ydiff ~ M3diff|    b3|  -0.0167| 0.1230| -0.1354|  0.8923| -0.2694| 0.2163|
## |  Ydiff ~ M1avg|    d1|  -0.0305| 0.0954| -0.3192|  0.7495| -0.2103| 0.1647|
## |  Ydiff ~ M2avg|    d2|  -0.0060| 0.0829| -0.0721|  0.9425| -0.1706| 0.1564|
## |  Ydiff ~ M3avg|    d3|  -0.1552| 0.1158| -1.3398|  0.1803| -0.3802| 0.0675|
## 
## 
## | Intercept| Label| Estimate|     SE|       z| P.value|    LLCI|   ULCI|
## |---------:|-----:|--------:|------:|-------:|-------:|-------:|------:|
## |   Ydiff~1|    cp|  -0.0315| 0.0163| -1.9284|  0.0538| -0.0654| 0.0004|
## |  M1diff~1|    a1|  -0.0271| 0.0173| -1.5667|  0.1172| -0.0618| 0.0074|
## |  M2diff~1|    a2|   0.0145| 0.0187|  0.7736|  0.4392| -0.0244| 0.0510|
## |  M3diff~1|    a3|   0.0153| 0.0160|  0.9587|  0.3377| -0.0155| 0.0458|
## |   M1avg~1|      |  -0.0000| 0.0180| -0.0000|  1.0000| -0.0342| 0.0370|
## |   M2avg~1|      |   0.0000| 0.0199|  0.0000|  1.0000| -0.0392| 0.0387|
## |   M3avg~1|      |  -0.0000| 0.0175| -0.0000|  1.0000| -0.0335| 0.0360|
## 
## 
## |       Variance| Estimate|     SE|      z| P.value|   LLCI|   ULCI|
## |--------------:|--------:|------:|------:|-------:|------:|------:|
## |   Ydiff~~Ydiff|   0.0275| 0.0035| 7.9564|  0.0000| 0.0191| 0.0326|
## | M1diff~~M1diff|   0.0308| 0.0037| 8.3519|  0.0000| 0.0234| 0.0378|
## | M2diff~~M2diff|   0.0323| 0.0042| 7.6592|  0.0000| 0.0241| 0.0409|
## | M3diff~~M3diff|   0.0264| 0.0038| 6.8832|  0.0000| 0.0192| 0.0340|
## |   M1avg~~M1avg|   0.0339| 0.0047| 7.1663|  0.0000| 0.0246| 0.0430|
## |   M2avg~~M2avg|   0.0407| 0.0051| 8.0309|  0.0000| 0.0301| 0.0503|
## |   M3avg~~M3avg|   0.0306| 0.0045| 6.8581|  0.0000| 0.0222| 0.0394|
## 
## 
## *************** TOTAL AND DIRECT EFFECT ***************
## 
## 
## |          Name|  Effect|     SE|       z|      p|    LLCI|   ULCI|
## |-------------:|-------:|------:|-------:|------:|-------:|------:|
## |  Total effect| -0.0316| 0.0165| -1.9158| 0.0554| -0.0645| 0.0004|
## | Direct effect| -0.0315| 0.0163| -1.9284| 0.0538| -0.0654| 0.0004|
## 
## 
## *************** INDIRECT EFFECTS ***************
## 
## 
## |      Name|  Effect|     SE|    LLCI|   ULCI|
## |---------:|-------:|------:|-------:|------:|
## |      ind1|  0.0014| 0.0031| -0.0041| 0.0087|
## |      ind2| -0.0012| 0.0029| -0.0081| 0.0036|
## |      ind3| -0.0003| 0.0027| -0.0071| 0.0048|
## | total ind| -0.0001| 0.0055| -0.0137| 0.0097|
## 
## 
## | Ind  |         Path         |
## |:----:|:--------------------:|
## | ind1 | X -> M1diff -> Ydiff |
## | ind2 | X -> M2diff -> Ydiff |
## | ind3 | X -> M3diff -> Ydiff |
## 
## 
## *************** CONTRAST INDIRECT EFFECTS ***************
## 
## 
## |        Name|  Effect|     SE|    LLCI|   ULCI|
## |-----------:|-------:|------:|-------:|------:|
## | ind1 - ind2|  0.0026| 0.0040| -0.0054| 0.0114|
## | ind1 - ind3|  0.0016| 0.0042| -0.0056| 0.0115|
## | ind2 - ind3| -0.0010| 0.0037| -0.0081| 0.0067|
## 
## 
## *************** MODERATION EFFECTS of X ***************
## 
## 
## | Name|  Effect|     SE|       z|      p|    LLCI|   ULCI|
## |----:|-------:|------:|-------:|------:|-------:|------:|
## |   d1| -0.0305| 0.0954| -0.3192| 0.7495| -0.2103| 0.1647|
## |   d2| -0.0060| 0.0829| -0.0721| 0.9425| -0.1706| 0.1564|
## |   d3| -0.1552| 0.1158| -1.3398| 0.1803| -0.3802| 0.0675|
## 
## 
## | Coefficient |      Path       |
## |:-----------:|:---------------:|
## |     d1      | M1diff -> Ydiff |
## |     d2      | M2diff -> Ydiff |
## |     d3      | M3diff -> Ydiff |
## 
## 
## *************** C1-C2 COEFFICIENTS ***************
## 
## 
## |  Name|  Effect|     SE|       z|      p|    LLCI|   ULCI|
## |-----:|-------:|------:|-------:|------:|-------:|------:|
## | X1_b1| -0.0654| 0.1116| -0.5856| 0.5581| -0.2968| 0.1384|
## | X0_b1| -0.0349| 0.1021| -0.3417| 0.7326| -0.2270| 0.1691|
## | X1_b2| -0.0874| 0.1211| -0.7211| 0.4709| -0.3133| 0.1533|
## | X0_b2| -0.0814| 0.1017| -0.8004| 0.4235| -0.2890| 0.1178|
## | X1_b3| -0.0942| 0.1507| -0.6253| 0.5318| -0.3941| 0.2098|
## | X0_b3|  0.0609| 0.1196|  0.5094| 0.6104| -0.1796| 0.2867|
## 
## 
## | Coefficient |       Path       |
## |:-----------:|:----------------:|
## |     b1      | M1diff -> Ydiff  |
## |     b2      | M2diff -> Ydiff  |
## |     b3      | M3diff -> Ydiff  |
## |     b12     | M1diff -> M2diff |
## |     b13     | M1diff -> M3diff |
## |     b23     | M2diff -> M3diff |
## 
## 
## *************** Bootstrapping NOTES ***************
## 
## Bootstrap confidence interval method used:  Percentile bootstrap 
## Number of bootstrap samples:  1000 
## Confidence level:  95 %
## Random seed used:  123 
## 
## 
## *************** STANDARDIZED RESULTS ***************
## 
## 
## |            Label| Estimate (Std)|       Z| P-value|    LLCI|   ULCI| Boot SE|
## |----------------:|--------------:|-------:|-------:|-------:|------:|-------:|
## |    Direct effect|        -0.1858| -1.9169|  0.0552| -0.3959| 0.0021|  0.0984|
## |               b1|        -0.0519| -0.5260|  0.5989| -0.2406| 0.1408|  0.0968|
## |               b2|        -0.0894| -0.8172|  0.4138| -0.2950| 0.1274|  0.1089|
## |               b3|        -0.0160| -0.1357|  0.8920| -0.2396| 0.2282|  0.1158|
## |               d1|        -0.0331| -0.3202|  0.7488| -0.2235| 0.1777|  0.1005|
## |               d2|        -0.0071| -0.0722|  0.9424| -0.1885| 0.1882|  0.0969|
## |               d3|        -0.1601| -1.3574|  0.1747| -0.3811| 0.0767|  0.1168|
## |               a1|        -0.1546| -1.5743|  0.1154| -0.3635| 0.0458|  0.1005|
## |               a2|         0.0806|  0.7691|  0.4418| -0.1382| 0.2896|  0.1061|
## |               a3|         0.0945|  0.9388|  0.3479| -0.0919| 0.2978|  0.1018|
## |   Ydiff ~~ Ydiff|         0.9578| 19.1423|  0.0000|  0.7570| 0.9797|  0.0592|
## | M1diff ~~ M1diff|         1.0000|      NA|      NA|      NA|     NA|      NA|
## | M2diff ~~ M2diff|         1.0000|      NA|      NA|      NA|     NA|      NA|
## | M3diff ~~ M3diff|         1.0000|      NA|      NA|      NA|     NA|      NA|
## |   M1avg ~~ M1avg|         1.0000|      NA|      NA|      NA|     NA|      NA|
## |   M1avg ~~ M2avg|         0.2898|  3.6158|  0.0003|  0.1168| 0.4385|  0.0829|
## |   M1avg ~~ M3avg|         0.3395|  4.1632|  0.0000|  0.1613| 0.4941|  0.0833|
## |   M2avg ~~ M2avg|         1.0000|      NA|      NA|      NA|     NA|      NA|
## |   M2avg ~~ M3avg|         0.3240|  4.0303|  0.0001|  0.1485| 0.4824|  0.0823|
## |   M3avg ~~ M3avg|         1.0000|      NA|      NA|      NA|     NA|      NA|
## |         M1avg ~1|        -0.0000| -0.0000|  1.0000| -0.1922| 0.2126|  0.1004|
## |         M2avg ~1|         0.0000|  0.0000|  1.0000| -0.2023| 0.1996|  0.1005|
## |         M3avg ~1|        -0.0000| -0.0000|  1.0000| -0.1989| 0.2053|  0.1012|
## |             ind1|         0.0080|  0.5111|  0.6093| -0.0236| 0.0498|  0.0181|
## |             ind2|        -0.0072| -0.5564|  0.5779| -0.0475| 0.0204|  0.0169|
## |             ind3|        -0.0015| -0.1328|  0.8944| -0.0403| 0.0283|  0.0159|
## |        total ind|        -0.0007| -0.0266|  0.9788| -0.0761| 0.0579|  0.0317|
## |     Total effect|        -0.1865| -1.8811|  0.0600| -0.3972| 0.0022|  0.0986|
## |        ind1-ind2|         0.0152|  0.8509|  0.3948| -0.0319| 0.0642|  0.0232|
## |        ind1-ind3|         0.0095|  0.4765|  0.6337| -0.0324| 0.0647|  0.0243|
## |        ind2-ind3|        -0.0057| -0.3782|  0.7053| -0.0479| 0.0415|  0.0216|
## |            X1_b1|        -0.0684| -0.5902|  0.5550| -0.2891| 0.1492|  0.1134|
## |            X0_b1|        -0.0353| -0.3315|  0.7403| -0.2352| 0.1781|  0.1046|
## |            X1_b2|        -0.0930| -0.7117|  0.4767| -0.3227| 0.1695|  0.1301|
## |            X0_b2|        -0.0858| -0.7925|  0.4280| -0.3031| 0.1244|  0.1072|
## |            X1_b3|        -0.0960| -0.6573|  0.5110| -0.3685| 0.2085|  0.1442|
## |            X0_b3|         0.0641|  0.5567|  0.5778| -0.1611| 0.2833|  0.1133|
```

```
## 
## Outcome Difference Model (Ydiff):
## Ydiff ~ cp*1 + b1*M1diff + b2*M2diff + b3*M3diff + d1*M1avg + d2*M2avg + d3*M3avg 
## 
## Mediator Difference Model (Chained Mediator - M1diff):
## M1diff ~ a1*1 
## 
## Mediator Difference Model (Parallel Mediators - M2diff, M3diff, ...):
## M2diff ~ a2*1
## M3diff ~ a3*1 
## 
## Indirect Effects:
## indirect1 := a1 * b1
## indirect2 := a2 * b2
## indirect3 := a3 * b3 
## 
## Total Indirect Effect:
## total_indirect := indirect1 + indirect2 + indirect3 
## 
## Total Effect:
## total_effect := cp + total_indirect 
## 
## Contrast of Indirect Effects:
## CI1vs2 := indirect1 - indirect2
## CI1vs3 := indirect1 - indirect3
## CI2vs3 := indirect2 - indirect3 
## 
## C1-C2 Coefficients:
## X1_b1 := (2*b1 + d1) / 2
## X0_b1 := X1_b1 - d1
## X1_b2 := (2*b2 + d2) / 2
## X0_b2 := X1_b2 - d2
## X1_b3 := (2*b3 + d3) / 2
## X0_b3 := X1_b3 - d3
```

## chained/serial mediation

We analyze a **Serial Mediation (`Serial = 1`)**, as MEMORE 3.0 supports only `Serial = 1`. 

### MEMORE 3.0 Analysis Report


````
## ```
##  
## Run MATRIX procedure:
## 
## *********************** MEMORE Procedure for SPSS Version 3.0 ***********************
## 
##                            Written by Amanda Montoya
## 
##                     Documentation available at github.com/akmontoya/MEMORE
## 
## **************************** ANALYSIS NOTES AND WARNINGS ****************************
## 
## Bootstrap confidence interval method used: Percentile bootstrap.
## 
## Number of bootstrap samples for bootstrap confidence intervals:
##   5000
## 
## The following variables were mean centered prior to analysis:
##  (        A2        +       A1       )        /2
##  (        B2        +       B1       )        /2
## 
## Level of confidence for all confidence intervals in output:
##       95.00
## 
## **************************************************************************************
## 
## Model:
##   1
## 
## Variables:
## Y =   C2       C1
## M1 =  A2       A1
## M2 =  B2       B1
## 
## Computed Variables:
## Ydiff =           C2        -       C1
## M1diff =          A2        -       A1
## M2diff =          B2        -       B1
## M1avg  = (        A2        +       A1       )        /2                         Centered
## M2avg  = (        B2        +       B1       )        /2                         Centered
## 
## Sample Size:
##   100
## 
## **************************************************************************************
## Outcome: Ydiff =  C2        -       C1
## 
## Model
##                Coef         SE          t          p       LLCI       ULCI
## constant      .0153      .0163      .9404      .3493     -.0170      .0477
## 
## Degrees of freedom for all regression coefficient estimates:
##   99
## 
## **************************************************************************************
## Outcome: M1diff = A2        -       A1
## 
## Model
##                Coef         SE          t          p       LLCI       ULCI
## constant     -.0271      .0176    -1.5385      .1271     -.0621      .0079
## 
## Degrees of freedom for all regression coefficient estimates:
##   99
## 
## **************************************************************************************
## Outcome: M2diff = B2        -       B1
## 
## Model Summary
##           R       R-sq        MSE          F        df1        df2          p
##       .2351      .0553      .0314     2.8371     2.0000    97.0000      .0635
## 
## Model
##               coeff         SE          t          p       LLCI       ULCI
## constant      .0208      .0179     1.1603      .2488     -.0148      .0564
## M1diff        .2333      .1010     2.3086      .0231      .0327      .4338
## M1avg        -.0578      .0963     -.6002      .5498     -.2489      .1333
## 
## Degrees of freedom for all regression coefficient estimates:
##   97
## 
## **************************************************************************************
## Outcome: Ydiff =  C2        -       C1
## 
## Model Summary
##           R       R-sq        MSE          F        df1        df2          p
##       .1720      .0296      .0269      .7238     4.0000    95.0000      .5778
## 
## Model
##                Coef         SE          t          p       LLCI       ULCI
## constant      .0160      .0167      .9563      .3413     -.0172      .0492
## M1diff       -.0360      .0962     -.3744      .7089     -.2270      .1549
## M2diff       -.1123      .0967    -1.1607      .2487     -.3043      .0798
## M1avg        -.0617      .0931     -.6619      .5097     -.2466      .1233
## M2avg        -.0733      .0875     -.8374      .4044     -.2469      .1004
## 
## Degrees of freedom for all regression coefficient estimates:
##   95
## 
## ************************* TOTAL, DIRECT, AND INDIRECT EFFECTS *************************
## 
## Total effect of X on Y
##      Effect         SE          t         df          p       LLCI       ULCI
##       .0153      .0163      .9404    99.0000      .3493     -.0170      .0477
## 
## Direct effect of X on Y
##      Effect         SE          t         df          p       LLCI       ULCI
##       .0160      .0167      .9563    95.0000      .3413     -.0172      .0492
## 
## Indirect Effect of X on Y through M
##           Effect     BootSE   BootLLCI   BootULCI
## Ind1       .0010      .0031     -.0045      .0084
## Ind2      -.0023      .0036     -.0111      .0033
## Ind3       .0007      .0010     -.0008      .0034
## Total     -.0006      .0048     -.0109      .0095
## 
## Indirect Key
## Ind1  'X'      ->       M1diff   ->       Ydiff
## Ind2  'X'      ->       M2diff   ->       Ydiff
## Ind3  'X'      ->       M1diff   ->       M2diff   ->       YDiff
## 
## Pairwise Contrasts Between Specific Indirect Effects
##           Effect     BootSE   BootLLCI   BootULCI
## (C1)       .0033      .0042     -.0042      .0128
## (C2)       .0003      .0034     -.0063      .0083
## (C3)      -.0030      .0041     -.0132      .0035
## 
## Contrast Key:
## (C1)  Ind1      -       Ind2
## (C2)  Ind1      -       Ind3
## (C3)  Ind2      -       Ind3
## 
## ------ END MATRIX -----
##  
## ```
````

### wsMed Analysis Report


``` r
result2 <- wsMed(
  data = example_data, #dataset
  M_C1 = c("A1","B1"), # A1/B1 is A/B mediator variable in condition 1 
  M_C2 = c("A2","B2"), # A2/B2 is A/B mediator variable in condition 2 
  Y_C1 = "C1", # C1 is outcome variable in condition 1
  Y_C2 = "C2", # C2 is outcome variable in condition 2
  form = "CN", # Parallel mediation
  standardized = TRUE,
)
print(result2,digits=4)
```

```
## 
## *************** VARIABLES ***************
## Variables:
## Y =  C2 C1 
## M1 =  A2 A1 
## M2 =  B2 B1 
## 
## Computed Variables:
## 
## 
## | Variable|                  Formula|
## |--------:|------------------------:|
## |    Ydiff|                  C2 - C1|
## |   M1diff|                  A2 - A1|
## |   M2diff|                  B2 - B1|
## |    M1avg| ( A2 + A1 ) / 2 Centered|
## |    M2avg| ( B2 + B1 ) / 2 Centered|
## 
## Sample Size:  100 
## Confidence Level:  95 %
## 
## 
## *************** MODEL FIT INDICES ***************
## 
## 
## |            Measure|   Value|
## |------------------:|-------:|
## |         Chi-Square|  5.7511|
## | Degrees of Freedom|  3.0000|
## |            p-Value|  0.1244|
## |                CFI|  0.4941|
## |                TLI| -0.5177|
## |              RMSEA|  0.0958|
## |     RMSEA Lower CI|  0.0000|
## |     RMSEA Upper CI|  0.2138|
## |               SRMR|  0.0502|
## 
## *************** REGRESSION PATHS, INTERCEPTS AND VARIANCES ***************
## 
## 
## |            Path| Label| Estimate|     SE|       z| P.value|    LLCI|   ULCI|
## |---------------:|-----:|--------:|------:|-------:|-------:|-------:|------:|
## |  Ydiff ~ M1diff|    b1|  -0.0360| 0.0942| -0.3823|  0.7022| -0.2431| 0.1217|
## |  Ydiff ~ M2diff|    b2|  -0.1123| 0.1127| -0.9966|  0.3190| -0.3369| 0.1166|
## |   Ydiff ~ M1avg|    d1|  -0.0617| 0.0752| -0.8199|  0.4123| -0.2035| 0.0981|
## |   Ydiff ~ M2avg|    d2|  -0.0733| 0.0858| -0.8541|  0.3930| -0.2546| 0.0854|
## | M2diff ~ M1diff|   b12|   0.2333| 0.1081|  2.1581|  0.0309|  0.0277| 0.4459|
## |  M2diff ~ M1avg|   d12|  -0.0578| 0.0844| -0.6847|  0.4935| -0.2318| 0.1019|
## 
## 
## | Intercept| Label| Estimate|     SE|       z| P.value|    LLCI|   ULCI|
## |---------:|-----:|--------:|------:|-------:|-------:|-------:|------:|
## |   Ydiff~1|    cp|   0.0160| 0.0166|  0.9634|  0.3353| -0.0160| 0.0476|
## |  M1diff~1|    a1|  -0.0271| 0.0173| -1.5667|  0.1172| -0.0618| 0.0074|
## |  M2diff~1|    a2|   0.0208| 0.0181|  1.1513|  0.2496| -0.0166| 0.0557|
## |   M1avg~1|      |  -0.0000| 0.0180| -0.0000|  1.0000| -0.0342| 0.0370|
## |   M2avg~1|      |   0.0000| 0.0199|  0.0000|  1.0000| -0.0392| 0.0387|
## 
## 
## |       Variance| Estimate|     SE|      z| P.value|   LLCI|   ULCI|
## |--------------:|--------:|------:|------:|-------:|------:|------:|
## |   Ydiff~~Ydiff|   0.0256| 0.0037| 6.8839|  0.0000| 0.0178| 0.0323|
## | M2diff~~M2diff|   0.0305| 0.0039| 7.8677|  0.0000| 0.0224| 0.0380|
## | M1diff~~M1diff|   0.0308| 0.0037| 8.3519|  0.0000| 0.0234| 0.0378|
## |   M1avg~~M1avg|   0.0339| 0.0047| 7.1663|  0.0000| 0.0246| 0.0430|
## |   M2avg~~M2avg|   0.0407| 0.0051| 8.0309|  0.0000| 0.0301| 0.0503|
## 
## 
## *************** TOTAL AND DIRECT EFFECT ***************
## 
## 
## |          Name| Effect|     SE|      z|      p|    LLCI|   ULCI|
## |-------------:|------:|------:|------:|------:|-------:|------:|
## |  Total effect| 0.0153| 0.0161| 0.9517| 0.3413| -0.0156| 0.0462|
## | Direct effect| 0.0160| 0.0166| 0.9634| 0.3353| -0.0160| 0.0476|
## 
## 
## *************** INDIRECT EFFECTS ***************
## 
## 
## |      Name|  Effect|     SE|    LLCI|   ULCI|
## |---------:|-------:|------:|-------:|------:|
## |      ind1|  0.0010| 0.0033| -0.0052| 0.0086|
## |      ind2| -0.0023| 0.0037| -0.0115| 0.0036|
## |     ind12|  0.0007| 0.0011| -0.0007| 0.0033|
## | total ind| -0.0006| 0.0050| -0.0110| 0.0094|
## 
## 
## |  Ind  |              Path              |
## |:-----:|:------------------------------:|
## | ind1  |      X -> M1diff -> Ydiff      |
## | ind2  |      X -> M2diff -> Ydiff      |
## | ind12 | X -> M1diff -> M2diff -> Ydiff |
## 
## 
## *************** CONTRAST INDIRECT EFFECTS ***************
## 
## 
## |         Name|  Effect|     SE|    LLCI|   ULCI|
## |------------:|-------:|------:|-------:|------:|
## |  ind1 - ind2|  0.0033| 0.0045| -0.0049| 0.0139|
## | ind1 - ind12|  0.0003| 0.0036| -0.0068| 0.0083|
## | ind2 - ind12| -0.0030| 0.0043| -0.0142| 0.0038|
## 
## 
## *************** MODERATION EFFECTS of X ***************
## 
## 
## | Name|  Effect|     SE|       z|      p|    LLCI|   ULCI|
## |----:|-------:|------:|-------:|------:|-------:|------:|
## |   d1| -0.0617| 0.0752| -0.8199| 0.4123| -0.2035| 0.0981|
## |   d2| -0.0733| 0.0858| -0.8541| 0.3930| -0.2546| 0.0854|
## |  d12| -0.0578| 0.0844| -0.6847| 0.4935| -0.2318| 0.1019|
## 
## 
## | Coefficient |       Path       |
## |:-----------:|:----------------:|
## |     d1      | M1diff -> Ydiff  |
## |     d2      | M2diff -> Ydiff  |
## |     d12     | M1diff -> M2diff |
## 
## 
## *************** C1-C2 COEFFICIENTS ***************
## 
## 
## |   Name|  Effect|     SE|       z|      p|    LLCI|   ULCI|
## |------:|-------:|------:|-------:|------:|-------:|------:|
## |  X1_b1| -0.0668| 0.0994| -0.6721| 0.5015| -0.2674| 0.1104|
## |  X0_b1| -0.0052| 0.1035| -0.0501| 0.9600| -0.2395| 0.1656|
## |  X1_b2| -0.1489| 0.1395| -1.0676| 0.2857| -0.4216| 0.1150|
## |  X0_b2| -0.0757| 0.0982| -0.7705| 0.4410| -0.2734| 0.1213|
## | X1_b12|  0.2044| 0.1095|  1.8668| 0.0619| -0.0263| 0.4032|
## | X0_b12|  0.2622| 0.1224|  2.1427| 0.0321|  0.0370| 0.5138|
## 
## 
## | Coefficient |       Path       |
## |:-----------:|:----------------:|
## |     b1      | M1diff -> Ydiff  |
## |     b2      | M2diff -> Ydiff  |
## |     b12     | M1diff -> M2diff |
## 
## 
## *************** Bootstrapping NOTES ***************
## 
## Bootstrap confidence interval method used:  Percentile bootstrap 
## Number of bootstrap samples:  1000 
## Confidence level:  95 %
## Random seed used:  123 
## 
## 
## *************** STANDARDIZED RESULTS ***************
## 
## 
## |            Label| Estimate (Std)|       Z| P-value|    LLCI|   ULCI| Boot SE|
## |----------------:|--------------:|-------:|-------:|-------:|------:|-------:|
## |    Direct effect|         0.0983|  0.9440|  0.3452| -0.0980| 0.3054|  0.1050|
## |               b1|        -0.0388| -0.3859|  0.6996| -0.2392| 0.1456|  0.1000|
## |               b2|        -0.1239| -1.0018|  0.3164| -0.3526| 0.1284|  0.1230|
## |               d1|        -0.0697| -0.8069|  0.4197| -0.2406| 0.0973|  0.0851|
## |               d2|        -0.0908| -0.8713|  0.3836| -0.2840| 0.1027|  0.1022|
## |               a1|        -0.1546| -1.5743|  0.1154| -0.3635| 0.0458|  0.1005|
## |               a2|         0.1159|  1.1464|  0.2516| -0.0923| 0.3128|  0.1025|
## |              b12|         0.2278|  2.1914|  0.0284|  0.0269| 0.4257|  0.1028|
## |              d12|        -0.0592| -0.6877|  0.4916| -0.2298| 0.1061|  0.0848|
## |   Ydiff ~~ Ydiff|         0.9656| 22.0492|  0.0000|  0.8034| 0.9913|  0.0489|
## | M2diff ~~ M2diff|         0.9446| 19.0559|  0.0000|  0.7975| 0.9956|  0.0511|
## | M1diff ~~ M1diff|         1.0000|      NA|      NA|      NA|     NA|      NA|
## |   M1avg ~~ M1avg|         1.0000|      NA|      NA|      NA|     NA|      NA|
## |   M1avg ~~ M2avg|         0.2898|  3.6158|  0.0003|  0.1168| 0.4385|  0.0829|
## |   M2avg ~~ M2avg|         1.0000|      NA|      NA|      NA|     NA|      NA|
## |         M1avg ~1|        -0.0000| -0.0000|  1.0000| -0.1922| 0.2126|  0.1004|
## |         M2avg ~1|         0.0000|  0.0000|  1.0000| -0.2023| 0.1996|  0.1005|
## |             ind1|         0.0060|  0.3763|  0.7067| -0.0321| 0.0546|  0.0201|
## |             ind2|        -0.0144| -0.7609|  0.4467| -0.0695| 0.0218|  0.0226|
## |            ind12|         0.0044|  0.7754|  0.4381| -0.0046| 0.0209|  0.0065|
## |        total ind|        -0.0040| -0.1518|  0.8793| -0.0671| 0.0570|  0.0310|
## |     Total effect|         0.0943|  0.9143|  0.3605| -0.0923| 0.3033|  0.1022|
## |        ind1-ind2|         0.0204|  1.0136|  0.3108| -0.0315| 0.0813|  0.0271|
## |       ind1-ind12|         0.0016|  0.0917|  0.9269| -0.0432| 0.0498|  0.0224|
## |       ind2-ind12|        -0.0187| -0.8257|  0.4090| -0.0806| 0.0236|  0.0260|
## |            X1_b1|        -0.0737| -0.6898|  0.4903| -0.2784| 0.1230|  0.1060|
## |            X0_b1|        -0.0039| -0.0352|  0.9719| -0.2414| 0.1894|  0.1113|
## |            X1_b2|        -0.1693| -1.0851|  0.2779| -0.4519| 0.1320|  0.1548|
## |            X0_b2|        -0.0785| -0.7265|  0.4675| -0.2882| 0.1340|  0.1073|
## |           X1_b12|         0.1982|  1.8364|  0.0663| -0.0258| 0.3974|  0.1067|
## |           X0_b12|         0.2574|  2.2014|  0.0277|  0.0368| 0.4893|  0.1156|
```

``` r
printGM(result2)
```

```
## 
## Outcome Difference Model (Ydiff):
## Ydiff ~ cp*1 + b1*M1diff + b2*M2diff + d1*M1avg + d2*M2avg 
## 
## Mediator Difference Model (Chained Mediator - M1diff):
## M1diff ~ a1*1 
## 
## Mediator Difference Model (Parallel Mediators - M2diff, M3diff, ...):
## M2diff ~ a2*1 + b12*M1diff + d12*M1avg 
## 
## Indirect Effects:
## indirect1 := a1 * b1
## indirect2 := a2 * b2
## indirect12 := a1 * b12 * b2 
## 
## Total Indirect Effect:
## total_indirect := indirect1 + indirect2 + indirect12 
## 
## Total Effect:
## total_effect := cp + total_indirect 
## 
## Contrast of Indirect Effects:
## CI1vs2 := indirect1 - indirect2
## CI1vs12 := indirect1 - indirect12
## CI2vs12 := indirect2 - indirect12 
## 
## C1-C2 Coefficients:
## X1_b1 := (2*b1 + d1)/2
## X0_b1 := X1_b1 - d1
## X1_b2 := (2*b2 + d2)/2
## X0_b2 := X1_b2 - d2
## X1_b12 := (2*b12 + d12)/2
## X0_b12 := X1_b12 - d12
```
