#!/bin/bash
#SBATCH --job-name sim_analysis13
#SBATCH --partition serial-short
#SBATCH --nodes 1
#SBATCH --tasks-per-node 1
#SBATCH --time 24:00:00
#SBATCH --mem 10G
#SBATCH --output sim_analysis13%j.out
#SBATCH --error sim_analysis13%j.err
#SBATCH --mail-type ALL
#SBATCH --mail-user yc47319@um.edu.mo

source /etc/profile
source /etc/profile.d/modules.sh

source /etc/profile
source /etc/profile.d/modules.sh

# DO NOTHING FOR NOW

# Adding modules
module add R/4.3.2

# Test
export OPENBLAS_NUM_THREADS=1
#R CMD BATCH --no-restore --no-save /icto/user/yc47319/ondemand/data/sys/myjobs/projects/default/1/sim_analysis13.R	/icto/user/yc47319/ondemand/data/sys/myjobs/projects/default/1/sim_analysis13.out
R CMD BATCH --no-restore --no-save sim_analysis13.R	sim_analysis13.out
