#' @title Print Formatted SEM Model Syntax
#'
#' @description Formats and prints the SEM model syntax generated by
#' `GenerateModelCN`, `GenerateModelCP`, `GenerateModelP`, and `GenerateModelPC`.
#' It organizes the equations into labeled sections for better readability.
#'
#' @param x A character string representing an SEM model syntax.
#' @param ... Additional arguments (not used).
#'
#' @return Invisibly returns the formatted SEM model syntax.
#' @examples
#' data(example_data)
#' head(example_data)
#' prepared_data <- PrepareData(
#'   data = example_data,
#'   M_before = c("A1", "B1",),
#'   M_after = c("A2", "B2"),
#'   Y_before = "C1",
#'   Y_after = "C2"
#' )
#' sem_model <- GenerateModelPC(prepared_data)
#' print.GM(sem_model)
#' @export

print.GM <- function(x, ...) {
  # **只有在 `x` 是 `list` 并且包含 `sem_model` 时，才提取 `sem_model`**
  if (is.list(x) && "sem_model" %in% names(x)) {
    x <- x$sem_model
  }

  # **确保 `x` 是单个字符串**
  if (!is.character(x) || length(x) != 1 || is.na(x) || x == "") {
    stop("Error in print.GM(): Input must be a non-empty character string representing an SEM model.")
  }

  # **解析 `\n` 确保换行正确**
  lines <- strsplit(x, "\n")[[1]]

  # **去除前后空格**
  lines <- trimws(lines)

  # **定义不同方程的分类**
  section_titles <- list(
    "Outcome Difference Model (Ydiff)" = "^Ydiff ",
    "Mediator Difference Model (Chained Mediator - M1diff)" = "^M1diff ",
    "Mediator Difference Model (Parallel Mediators - M2diff, M3diff, ...)" = "^M[2-9]diff ",
    "Indirect Effects" = "^indirect",
    "Total Indirect Effect" = "^total_indirect",
    "Total Effect" = "^total_effect",
    "Contrast of Indirect Effects" = "^CI\\d+vs",
    "Pre-Post Coefficients" = "^X[01]_b"
  )

  # **遍历不同部分，按类别格式化输出**
  for (title in names(section_titles)) {
    section_lines <- grep(section_titles[[title]], lines, value = TRUE, perl = TRUE)
    if (length(section_lines) > 0) {
      cat("\n", title, ":\n", sep = "")
      cat(paste(section_lines, collapse = "\n"), "\n")
    }
  }

  # **返回原始模型字符串（不影响后续使用）**
  invisible(x)
}
